
import java.awt.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arunb
 */
public class Feedback extends javax.swing.JFrame {

    /**
     * Creates new form Feedback
     */
    public Feedback() {
        setTitle("Karnaugh Map © Book_Programmers");
        setSize(700,580);
        setLocation(477,80);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setLayout(null);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/k.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        S = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rate us:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 40));

        L.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        L.setForeground(new java.awt.Color(255, 255, 255));
        L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 200, 24));

        S.setForeground(new java.awt.Color(102, 102, 102));
        S.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SMouseDragged(evt);
            }
        });
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 320, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseDragged
        L.setText("Good");
        int feed=S.getValue();
        if(feed>=0&&feed<=20)
            L.setText("Very Poor");
        else if(feed>20&&feed<=40)
            L.setText("Satisfactory");
        else if(feed>40&&feed<=60)
            L.setText("Good");
        else if(feed>60&&feed<=80)
            L.setText("Very Good");
        else
            L.setText("Excellent!");
    }//GEN-LAST:event_SMouseDragged

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked
        int feed=S.getValue();
        if(feed>=0&&feed<=20)
            L.setText("Very Poor");
        else if(feed>20&&feed<=40)
            L.setText("Satisfactory");
        else if(feed>40&&feed<=60)
            L.setText("Good");
        else if(feed>60&&feed<=80)
            L.setText("Very Good");
        else
            L.setText("Excellent!");
    }//GEN-LAST:event_SMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JSlider S;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
